IF OBJECT_ID('dbo.USP_GET_ROUND_STATS') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_GET_ROUND_STATS AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_GET_ROUND_STATS
@ROUND_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		  SELECT NUMBER, PAR, SCORE, GIR, FwyHit, Putts, Handicap, Yardage   FROM dbo.HoleStats AS s 
				INNER JOIN dbo.Holes AS h
  
				 ON s.HoleId = h.HoleId
				 WHERE RoundId = @ROUND_ID
	END;
END;
GO