IF OBJECT_ID('dbo.USP_GET_HOLE_STATS') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_GET_HOLE_STATS AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_GET_HOLE_STATS
@ROUND_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		SELECT * FROM [GOLF].[dbo].[HoleStats]
		WHERE RoundId = @ROUND_ID
	END;
END;
GO