IF OBJECT_ID('dbo.USP_INS_COURSE') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_INS_COURSE AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_INS_COURSE
@NAME NVARCHAR(50),
@CITY NVARCHAR(50),
@STATE NVARCHAR(50),
@PAR INT = NULL

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		  INSERT INTO dbo.[Courses] (Name, City, State, Par)

	  VALUES
	  (@NAME, @CITY, @STATE, @PAR)
	END;
END;
GO