IF OBJECT_ID('dbo.USP_GET_COURSE_STATS') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_GET_COURSE_STATS AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_GET_COURSE_STATS
@COURSE_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		SELECT * FROM [GOLF].[dbo].[CourseStats]
		WHERE CourseId = @COURSE_ID
	END;
END;
GO