IF OBJECT_ID('dbo.USP_INS_PLAYER') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_INS_PLAYER AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_INS_PLAYER
@NAME VARCHAR(50),
@HANDICAP INT,
@AGE INT,
@IS_MALE BIT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		  INSERT INTO dbo.Players(Name, Handicap, Age, IsMale)
		  VALUES  ( @NAME,
					@HANDICAP,
					@AGE,
					@IS_MALE)
	END;
END;
GO