IF OBJECT_ID('dbo.USP_GET_HOLES') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_GET_HOLES AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_GET_HOLES
@COURSE_ID INT,
@TEE_MARKER_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		SELECT * FROM [GOLF].[dbo].[Holes]
		WHERE CourseId = @COURSE_ID AND TeeMarkerId = @TEE_MARKER_ID
	END;
END;
GO