IF OBJECT_ID('dbo.USP_GET_ROUNDS') IS NULL
BEGIN
    EXEC('CREATE PROC dbo.USP_GET_ROUNDS AS SET NOCOUNT ON;');
END
GO

ALTER PROCEDURE dbo.USP_GET_ROUNDS
@COURSE_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	BEGIN
		SELECT * FROM [GOLF].[dbo].[Rounds]
		WHERE CourseId = @COURSE_ID
	END;
END;
GO